<a href="https://colab.research.google.com/github/subbubana/fmml2021/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# The basics


In [ ]:
a = np.array([1,2,3], dtype="int16") # by default int takes "int64"
print(a)
print(a.ndim) # print the dimensions of the array
print(a.shape) # prints the shape of the array

[1 2 3]
1
(3,)


In [ ]:
b = np.array([[1.0,2,3],[5,6,7]]) # the interger values are typecasted to float as float has high priority
print(b)
print(b.shape)
print(b.ndim)

[[1. 2. 3.]
 [5. 6. 7.]]
(2, 3)
2


In [ ]:
#get the type of the array
b.dtype

dtype('float64')

In [ ]:
#size of an element
itm_size = a.itemsize # retuns the size of element in bytes
total_size = a.nbytes # returns total size of the array in bytes
print(itm_size, total_size)

2 6


**Accessing/changing specific elements, rows or columns**
Accessing the elements in an array is similar to a list for 1D array. While accessing the elements in the nD arrays, you will have to mention the postion in each dimension to access the element.

In [ ]:
#Lets do some array operations; redeclaring the array 'a'
a = np.array([[2,3,5,4,1,8,9],[9,5,4,3,8,2,1]])
print(a)
print(a.shape)

[[2 3 5 4 1 8 9]
 [9 5 4 3 8 2 1]]
(2, 7)


In [ ]:
#accessing the items -- specify row and column
a[1,5] # second row and sixth column

2

In [ ]:
print(a[0,:]) # to get first row of elements
print(a[:,1]) # to get second column of elements

[2 3 5 4 1 8 9]
[3 5]


In [53]:
#giving the step size while printing the elemetns [startindex:stopindex:stepsize]
print(a[1,::2]) # print the second row of elements with a step size of 2

#can also try negative indexing
print(a)
print(a[0,1:5:-2])
print(a[0,::-2])

[9 4 8 1]
[[ 2 20  5  4  1 10  9]
 [ 9 21  4  3  8 10  1]]
[]
[9 1 5 2]


In [ ]:
#Updating the values in an array
a[1,5] = 100 # changing value in a certain position
print(a)
a[:,5]=10 #all specified elements will take value 10
print(a)
a[:,1] = [20,21] # giving equal number of values for positions
print(a)

[[  2   3   5   4   1   8   9]
 [  9   5   4   3   8 100   1]]
[[ 2  3  5  4  1 10  9]
 [ 9  5  4  3  8 10  1]]
[[ 2 20  5  4  1 10  9]
 [ 9 21  4  3  8 10  1]]


In [55]:
#3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [58]:
#get sepcific element -- work outside in
print(c[0,1,1]) # prints 4
print(c[1,0,1]) # prints 6

4
6


In [ ]:
# replacing specific elements -- check the error
c[:,1,:1] = [[9,10]]
print(c)

In [68]:
c[:,1,:1] = [[9],[10]]
print(c)

[[[ 1  2]
  [ 9  4]]

 [[ 5  6]
  [10  8]]]


# Initializing different types of arrays

In [ ]:
#All zeros matrix
np.zeros((2,3,4),dtype="int32")

In [76]:
#all ones
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [81]:
#any other numner
full_arr = np.full((2,3),10,dtype="float")
print(full_arr.itemsize)
print(full_arr)

8
[[10. 10. 10.]
 [10. 10. 10.]]


In [82]:
# full_like uses the shape of existing array
np.full_like(full_arr,20)

array([[20., 20., 20.],
       [20., 20., 20.]])

In [90]:
#initializing array with random values
np.random.rand(2,3) # decimals
np.random.randint(10,20,size=(3,3)) # array with random integer values in the randge 10 to 20

array([[18, 15, 10],
       [15, 15, 10],
       [10, 13, 12]])

In [86]:
np.random.random_sample(a.shape)

array([[0.85211086, 0.42422809, 0.34751556, 0.95666573, 0.71061887,
        0.26073621, 0.29153818],
       [0.52476022, 0.8368856 , 0.0723494 , 0.24124029, 0.7619537 ,
        0.49105741, 0.7755865 ]])

In [91]:
#The identity matrix is a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
#repeat the array
arr = np.array([[1,2,3]])
rp = np.repeat(arr,3,axis=0)
print(rp)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
